"""Add duration to workout models

Revision ID: 6591fe4b79c3
Revises: eaf3eee36644
Create Date: 2025-11-23 14:57:44.771208

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6591fe4b79c3'
down_revision: Union[str, Sequence[str], None] = 'eaf3eee36644'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercise_logs', sa.Column('completed_duration_minutes', sa.Integer(), nullable=True))
    op.add_column('program_exercises', sa.Column('prescribed_duration_minutes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('program_exercises', 'prescribed_duration_minutes')
    op.drop_column('exercise_logs', 'completed_duration_minutes')
    # ### end Alembic commands ###
