"""add_role_to_trainees

Revision ID: 902e74c7ea6b
Revises: 0b6cd66ac5ca
Create Date: 2025-11-05 20:53:35.610931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '902e74c7ea6b'
down_revision: Union[str, Sequence[str], None] = '0b6cd66ac5ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trainees', sa.Column('role', sa.Enum('ADMIN', 'TRAINER', 'TRAINEE', name='userrole'), nullable=True, server_default='TRAINEE'))
    op.execute("UPDATE trainees SET role = 'TRAINEE' WHERE role IS NULL")
    op.alter_column('trainees', 'role', existing_type=sa.Enum('ADMIN', 'TRAINER', 'TRAINEE', name='userrole'), nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('trainees', 'role')
    # ### end Alembic commands ###
