"""Add InBody health metrics

Revision ID: eaf3eee36644
Revises: ca509f59d436
Create Date: 2025-11-23 14:42:37.455354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eaf3eee36644'
down_revision: Union[str, Sequence[str], None] = 'ca509f59d436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('health_metrics', sa.Column('skeletal_muscle_mass_kg', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('body_fat_mass_kg', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('bmi', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('total_body_water_l', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('protein_kg', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('minerals_kg', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('basal_metabolic_rate_kcal', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('visceral_fat_level', sa.Integer(), nullable=True))
    op.add_column('health_metrics', sa.Column('inbody_score', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('left_arm_lean_kg', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('right_arm_lean_kg', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('left_leg_lean_kg', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('right_leg_lean_kg', sa.Float(), nullable=True))
    op.add_column('health_metrics', sa.Column('trunk_lean_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('health_metrics', 'trunk_lean_kg')
    op.drop_column('health_metrics', 'right_leg_lean_kg')
    op.drop_column('health_metrics', 'left_leg_lean_kg')
    op.drop_column('health_metrics', 'right_arm_lean_kg')
    op.drop_column('health_metrics', 'left_arm_lean_kg')
    op.drop_column('health_metrics', 'inbody_score')
    op.drop_column('health_metrics', 'visceral_fat_level')
    op.drop_column('health_metrics', 'basal_metabolic_rate_kcal')
    op.drop_column('health_metrics', 'minerals_kg')
    op.drop_column('health_metrics', 'protein_kg')
    op.drop_column('health_metrics', 'total_body_water_l')
    op.drop_column('health_metrics', 'bmi')
    op.drop_column('health_metrics', 'body_fat_mass_kg')
    op.drop_column('health_metrics', 'skeletal_muscle_mass_kg')
    # ### end Alembic commands ###
